apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movie-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: movie-server
    spec:
      containers:
        - name: movie-server
          image: gcr.io/govindacloud09072019/movie-server
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: movie-server
  labels:
    name: movie-server
spec:
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: springboot-rest-gcp
  type: LoadBalancer